pipeline:
  name: test-shashank-triggers
  identifier: testshashanktriggers
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: hello
        identifier: hello
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Chaos
                  name: Chaos_1
                  identifier: Chaos_1
                  spec:
                    experimentRef: 823dd580-8530-4bfe-a0fe-815727c81eaa
                    expectedResilienceScore: 100
              - step:
                  type: Chaos
                  name: Chaos_2
                  identifier: Chaos_2
                  spec:
                    experimentRef: a4808543-0caa-4470-a514-bf2219441162
                    expectedResilienceScore: 100
              - step:
                  type: Container
                  name: Container_1
                  identifier: Container_1
                  spec:
                    connectorRef: <+input>
                    image: <+input>
                    command: echo
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: <+input>
                        namespace: <+input>
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    reports:
                      type: JUnit
                      spec:
                        paths: []
                    outputVariables: []
                    envVariables:
                      ORG_ID: <+pipeline.ORG_ID>
                  timeout: <+input>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Ignore
  variables:
    - name: namespace
      type: String
      description: ""
      required: false
      value: <+trigger.payload.namespace>
